// <auto-generated />
using System;
using GerenciadorDeTarefa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorDeTarefa.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GerendiadorDeTarefa.Domain.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pessoa");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("PessoaNome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pessoa_nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.HasKey("IdPessoa")
                        .HasName("pk_pessoa");

                    b.ToTable("pessoa", (string)null);
                });

            modelBuilder.Entity("GerendiadorDeTarefa.Domain.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tarefa_id");

                    b.Property<string>("CategoriaTarefaDescricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("categoria_tarefa_descricao");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime>("DataConclusaoEsperada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_conclusao_esperada");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio");

                    b.Property<int>("EnumCategoriaTarefa")
                        .HasColumnType("int")
                        .HasColumnName("enum_categoria_tarefa");

                    b.Property<int>("EnumPrioridadeEnum")
                        .HasColumnType("int")
                        .HasColumnName("enum_prioridade_enum");

                    b.Property<string>("PrioridadeDescriscao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("prioridade_descriscao");

                    b.Property<int>("ResponsavelTarefaIdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("responsavel_tarefa_id_pessoa");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<bool>("TarefaConcluida")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tarefa_concluida");

                    b.Property<string>("TarefaDescriscao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tarefa_descriscao");

                    b.HasKey("TarefaId")
                        .HasName("pk_tarefa");

                    b.HasIndex("ResponsavelTarefaIdPessoa")
                        .HasDatabaseName("ix_tarefa_responsavel_tarefa_id_pessoa");

                    b.ToTable("tarefa", (string)null);
                });

            modelBuilder.Entity("GerendiadorDeTarefa.Domain.Tarefa", b =>
                {
                    b.HasOne("GerendiadorDeTarefa.Domain.Pessoa", "ResponsavelTarefa")
                        .WithMany()
                        .HasForeignKey("ResponsavelTarefaIdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tarefa_pessoa_responsavel_tarefa_id_pessoa");

                    b.Navigation("ResponsavelTarefa");
                });
#pragma warning restore 612, 618
        }
    }
}
